employee:
 build: Employee
 ports:
  - "8080"
 links:
  - mongodb
  - kafka
booking:
 build: Booking
 ports:
  - "8080"
 links:
  - mongodb
  - kafka
mongodb:
 image: mongo
kafka:
    image: 'wurstmeister/kafka'
    ports:
     - "9092:9092"
    hostname: kafka
    links: 
     - zookeeper
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=kafka
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_PORT=9092
     - KAFKA_HEAP_OPTS="-Xmx256M -Xms128M"
zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
ha_employee:
    image: tutum/haproxy
    links:
      - employee
    ports:
      - "8080:80" 
ha_booking:
    image: tutum/haproxy
    links:
      - booking
    ports:
      - "8081:80"  
